<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);NU1901;NU1902;NU1903;NU1904</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="MassTransit.TestFramework" />
    <PackageReference Include="Testcontainers.Azurite" />
    <PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" />
    <PackageReference Include="Azure.Storage.Blobs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DocProcessing.Ingest.Service\DocProcessing.Ingest.Service.csproj" />
    <ProjectReference Include="..\..\src\DocProcessing.Contracts\DocProcessing.Contracts.csproj" />
  </ItemGroup>

</Project>
